### PR TITLE
fix(zfs): timer stop when checkVolCreation exit

### PR DESCRIPTION
**Pull request by rfyiamcool**
## Pull Request template

**Why is this PR required? What issue does it fix?**:

when func is end, we need to stop timer. 

**What this PR does?**:

when func is end, we need to stop timer. 

**Does this PR require any upgrade changes?**:

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Fixes #<issue number>
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated?
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/website is used to track them:

**PLEASE REMOVE BELOW INFORMATION BEFORE SUBMITTING**

The PR title message must follow convention:
   `<type>(<scope>): <subject>`.

Where: <br />
- `type` is defining if release will be triggering after merging submitted changes, details in [CONTRIBUTING.md](../CONTRIBUTING.md).
    Most common types are:
    - `feat`      - for new features, not a new feature for build script
    - `fix`       - for bug fixes or improvements, not a fix for build script
    - `chore`     - changes not related to production code
    - `docs`      - changes related to documentation
    - `style`     - formatting, missing semi colons, linting fix etc; no significant production code changes
    - `test`      - adding missing tests, refactoring tests; no production code change
    - `refactor`  - refactoring production code, eg. renaming a variable or function name, there should not be any significant production code changes

- `scope` is a single word that best describes where the changes fit.
  Most common scopes are like:
    - data engine (`localpv`, `jiva`, `cstor`)
    - feature (`provisioning`, `backup`, `restore`, `exporter`)
    - code component (`api`, `webhook`, `cast`, `upgrade`)
    - test (`tests`, `bdd`)
    - chores (`version`, `build`, `log`, `travis`)

- `subject` is a single line brief description of the changes made in the pull request.

### CODE REVIEW

**Comment by Abhinandan-Purkait** [comment]
@rfyiamcool Please sign your commit. Can you please explain the change and the current issue on the PR description?

**Comment by rfyiamcool** [comment]
> @rfyiamcool Please sign your commit. Can you please explain the change and the current issue on the PR description?

done 😁

**Comment by Abhinandan-Purkait** [comment]
> > @rfyiamcool Please sign your commit. Can you please explain the change and the current issue on the PR description?
> 
> done 😁

I still see the DCO failing. You should check the steps here https://github.com/openebs/zfs-localpv/pull/600/checks?check_run_id=32630888366

**Comment by rfyiamcool** [comment]
> > > @rfyiamcool Please sign your commit. Can you please explain the change and the current issue on the PR description?
> > 
> > 
> > done 😁
> 
> I still see the DCO failing. You should check the steps here https://github.com/openebs/zfs-localpv/pull/600/checks?check_run_id=32630888366

Sorry, it's okay now. 😁

**Review by tiagolobocastro — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by Abhinandan-Purkait** [comment]
@rfyiamcool Thanks, can you please rebase, once that is done, we can do the merging.

**Comment by rfyiamcool** [comment]
> @rfyiamcool Thanks, can you please rebase, once that is done, we can do the merging.

done

**Review by niladrih — APPROVED** [review]

**Pull request merged**
