### PR TITLE
refactor pkg/zfs/mount.go Remove MountInfo struct from api 

### LINKED ISSUE #142: remove MountInfo struct from the API file
**Describe the problem/challenge you have**

MountInfo struct is in memory struct used to keep the information related to mounting the volume. It should not be there in the versioned api file. 

https://github.com/openebs/zfs-localpv/blob/307861282a5976e4a4a8e2d52f5f2fe94b9d8305/pkg/apis/openebs.io/zfs/v1alpha1/zfsvolume.go#L46

**Describe the solution you'd like**

Move the MountInfo struct to the pkg/zfs/mount.go file from pkg/apis/openebs.io/zfs/v1alpha1/zfsvolume.go

### PR DESCRIPTION
**Pull request by codegagan**
## Pull Request template

Please, go through these steps before you submit a PR.

**Why is this PR required? What issue does it fix?**: Fixes #142 

**What this PR does?**: refactors the code to move MountInfo struct from api files

**Does this PR require any upgrade changes?**: No

**If the changes in this PR are manually verified, list down the scenarios covered:**: make all

**Any additional information for your reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Fixes #142 
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [x] Has the change log section been updated?
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

### CODE REVIEW

**Comment by codegagan** [comment]
@pawanpraka1 Request you to review.

**Review by pawanpraka1 — COMMENTED** [review]
Thanks for this PR @codegagan. Changes are fine. I have given few minor comments.

**Comment by codegagan** [comment]
@pawanpraka1 have implemented the suggestions. Also, if you considering this PR for merge, please add label `hacktoberfest-accepted`.

**Review by pawanpraka1 — APPROVED** [review]
looks good.

**Comment by pawanpraka1** [comment]
Thank you @codegagan for working on this PR.

You can sign up for Hacktoberfest swag from MayaData by entering details here: https://github.com/mayadata-io/swag/issues/new/choose

**Pull request merged**
