### PR TITLE
docs(localpv): comment fixes & better documentation related to thinprovision parameter

### LINKED ISSUE #560: No clear default value for thin provisioning of filesystems
**What steps did you take and what happened:**
I created a simple storageClass as follows :
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: openebs-zfspv
allowVolumeExpansion: true
parameters:
 recordsize: "128k"
 fstype: "zfs"
 poolname: "zfspv-pool"
provisioner: zfs.csi.openebs.io
```
and then created both a PVC and a Pod in order to trigger the CSI provisioner which then creates a zfs FS

**What did you expect to happen:**
I would have expected a thick provisioning aka reservation or refreservation property on the created zfs FS but I got none.

As there is no default value in the documentation : https://github.com/openebs/zfs-localpv/blob/develop/docs/storageclasses.md#thinprovision-optional-parameter,
I had a look at the code and there is, it seems, a `no` default value : https://github.com/openebs/zfs-localpv/blob/1c4a810e5302c7b4a176ca109f9e11bd5fd6d8a9/pkg/apis/openebs.io/zfs/v1alpha1/zfsvolume.go#L151

**The output of the following commands will help us better understand what's going on**:
```
zfs list -o name,quota,refreserv,reserv
NAME                                                 QUOTA  REFRESERV  RESERV
zfspv-pool                                            none       none    none
zfspv-pool/pvc-b16e1228-ff11-4101-a117-01f65ce3257e    21G       none    none
```

**Anything else you would like to add:**
I would suggest :
- to remove the comment in the code as there is actually no default behavior within this CSI provisioner
- add in the documentation an information about the default behavior of ZFS (which is thinprovision: yes, at least in my setup)

Also it is worth to be noted that setting `thinprovision: "no"` works as expected, my problem is limited to the default behavior.

**Environment:**
- LocalPV-ZFS version:  zfs-localpv-2.4.0
- Kubernetes version (use `kubectl version`): v1.27.12
- Kubernetes installer & version: v1.27.12+rke2r1
- Cloud provider or hardware configuration: VM on ProxmoxVE
- OS (e.g. from `/etc/os-release`): Flatcar 3815.2.0

### PR DESCRIPTION
**Pull request by abuisine**
## Pull Request template

Please, go through these steps before you submit a PR.

**Why is this PR required? What issue does it fix?**:
Fixes #560 

**What this PR does?**:
Remove misleading comments and enrich documentation.

**Does this PR require any upgrade changes?**:
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
N/A

**Any additional information for your reviewer?** :
N/A

**Checklist:**
- [x] Fixes #<issue number>
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated?
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [x] (Optional) If documentation changes are required, which issue on https://github.com/openebs/website is used to track them:

### CODE REVIEW

**Review by Abhinandan-Purkait — CHANGES_REQUESTED** [review]
Hi @abuisine, can you please undo the changes on the files `v1/zfsvolume.go` and `v1alpha1/zfsvolume.go`. Those changes cannot just go in without running the manifest generation and the kubegen to generate the autogenerated code. We will take that up on a different PR as running the generators will change a few files.

LGTM, on the doc changes.

Also you might want to sign your commit for DCO to pass. Thanks

**Review by Abhinandan-Purkait — APPROVED** [review]
LGTM. Thanks @niladrih @avishnu @tiagolobocastro @sinhaashish  Can we have some more reviews here?

**Comment by Abhinandan-Purkait** [comment]
@balaharish7 Please update [here](https://openebs.io/docs/user-guides/local-storage-user-guide/local-pv-zfs/zfs-configuration#thinprovision-optional-parameter) accordingly once this is merged.

**Review by tiagolobocastro — APPROVED** [review]

**Comment by abuisine** [comment]
@Abhinandan-Purkait I just did, and rebased, should be good to go

**Comment by Abhinandan-Purkait** [comment]
@abuisine Thanks.

**Pull request merged**
