### PR TITLE
fix(ci): add openebs namespace in ci

### LINKED ISSUE #579: CI fails
**What steps did you take and what happened:**
The ci fails 

**What did you expect to happen:**
Ci to pass

**Anything else you would like to add:**
The logs of controller says
```
********************* ZFS Agent logs *********************************
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].metadata.name}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":""}}


error: resource name may not be empty


error: You must provide one or more resources by argument or filename.
Example resource specifications include:
   '-f rsrc.yaml'
   '--filename=rsrc.json'
   '<resource> <name>'
   '<resource>'

```
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- LocalPV-ZFS version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by sinhaashish**
## Pull Request template

Please, go through these steps before you submit a PR.

**Why is this PR required? What issue does it fix?**:
The Ci was failing

**What this PR does?**:
add namespce in ci

**Does this PR require any upgrade changes?**:
no

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Any additional information for your reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [X] Fixes #<issue number>
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated?
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/website is used to track them:

**PLEASE REMOVE BELOW INFORMATION BEFORE SUBMITTING**

The PR title message must follow convention:
   `<type>(<scope>): <subject>`.

Where: <br />
- `type` is defining if release will be triggering after merging submitted changes, details in [CONTRIBUTING.md](../CONTRIBUTING.md).
    Most common types are:
    - `feat`      - for new features, not a new feature for build script
    - `fix`       - for bug fixes or improvements, not a fix for build script
    - `chore`     - changes not related to production code
    - `docs`      - changes related to documentation
    - `style`     - formatting, missing semi colons, linting fix etc; no significant production code changes
    - `test`      - adding missing tests, refactoring tests; no production code change
    - `refactor`  - refactoring production code, eg. renaming a variable or function name, there should not be any significant production code changes

- `scope` is a single word that best describes where the changes fit.
  Most common scopes are like:
    - data engine (`localpv`, `jiva`, `cstor`)
    - feature (`provisioning`, `backup`, `restore`, `exporter`)
    - code component (`api`, `webhook`, `cast`, `upgrade`)
    - test (`tests`, `bdd`)
    - chores (`version`, `build`, `log`, `travis`)

- `subject` is a single line brief description of the changes made in the pull request.
Fixes #579

### CODE REVIEW

**Review by niladrih — DISMISSED** [review]

**Comment by Abhinandan-Purkait** [comment]
Add the changes on the other workflow files, as we did for bdd job.

**Comment by sinhaashish** [comment]
> Add the changes on the other workflow files, as we did for bdd job.

Only added in the yaml files. addition of kubeconfig was erroring out as the ci test was not able to find the cluster
```
        env:
          OPENEBS_NAMESPACE: openebs
```

**Comment by niladrih** [comment]
This is no longer required in the workflows, I think.
```
      - name: Setting environment variables
        run: |
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
          echo "OPENEBS_NAMESPACE=openebs" >> $GITHUB_ENV
```

**Comment by sinhaashish** [comment]
> ci test was not able to find the cluster

after removing this  ci test was not able to find the cluster

**Review by niladrih — COMMENTED** [review]
```yaml
      - name: Running tests
        env:
          OPENEBS_NAMESPACE: "openebs"
          KUBECONFIG: "~/.kube/config"
```

Also remove
```yaml
      - name: Setting environment variables
        run: |
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
          echo "OPENEBS_NAMESPACE=openebs" >> $GITHUB_ENV
```

Could you please try with these changes?

**Comment by Abhinandan-Purkait** [comment]
Remove `echo "OPENEBS_NAMESPACE=openebs" >> $GITHUB_ENV` from the workflows.

**Review by niladrih — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Pull request merged**
