### PR TITLE
docs(localpv): fix ZFS block StorageClass YAML

### PR DESCRIPTION
**Pull request by t3hmrman**
## Pull Request template

Please, go through these steps before you submit a PR.

**Why is this PR required? What issue does it fix?**:

The `StorageClass` YAML for raw block volume support didn't match the [`StorageClass` spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#storageclass-v1-storage-k8s-io)

**What this PR does?**:

Changes the documentation

**Does this PR require any upgrade changes?**:

No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

N/A

**Any additional information for your reviewer?** :

N/A

**Checklist:**
- [-] Fixes #<issue number>
  - There is no tracking issue for this fix
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated?
- [-] Commit has unit tests
- [-] Commit has integration tests
- [-] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [-] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

### CODE REVIEW

**Review by pawanpraka1 — APPROVED** [review]
Looks good. Thanks for this PR @t3hmrman

**Comment by t3hmrman** [comment]
No problem @pawanpraka1 thanks for all the awesome work -- ZFS LocalPV is working great for me :)

**Comment by pawanpraka1** [comment]
@t3hmrman thanks, Would you like to mention your use case in our Adopters.md openebs/openebs#2719.

**Comment by t3hmrman** [comment]
Hey @pawanpraka1 I'd love to -- I'll take a look and make a comment!

**Pull request merged**
