### PR TITLE
feat(localpv): Add regex to handle zstd levels [1-19]

### LINKED ISSUE #438: Support setting compression to zstd-{1-19}
**Describe the problem/challenge you have**
Currently, the CRD for a zv doesn't allow compression to be set to zstd variants. ie zstd-6.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Update the regex to allow zstd variants to be set

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- ZFS-LocalPV version
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jnels124**
## Pull Request template

Please, go through these steps before you submit a PR.

**Why is this PR required? What issue does it fix?**:
allow setting the compression to zstd with levels 

**What this PR does?**:
Updates CRDs for volumes, snapshots, and restores to allow zstd compression with specific level

**Does this PR require any upgrade changes?**:
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:
Manually applied CRD's (also re ran verification steps when using helm)
Edited existing zv with compression set to zstd-12. Verified the zpool on the node was updated accordingly. 
Performed write tests with known compressed size and confirmed compression level change was applied to new data.
**Any additional information for your reviewer?** :

**Checklist:**
- [x] Fixes #438 
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [x] Has the change log section been updated?
- [x] Commit has unit tests
- [x] Commit has integration tests
- [x] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [x] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

### CODE REVIEW

**Comment by niladrih** [comment]
Hey @jnels124, thank you for your contribution! Could you please rebase your PR please? Thanks..

**Comment by jnels124** [comment]
@niladrih I have rebased my branch.

**Comment by jnels124** [comment]
@niladrih believe there was an error in my previous rebase. I have fixed.

**Review by hrudaya21 — APPROVED** [review]

**Review by avishnu — APPROVED** [review]
lgtm

**Comment by niladrih** [comment]
These changes have been included in https://github.com/openebs/zfs-localpv/pull/461, closing this one. This is available in the released version v2.3.0.

**Pull request closed without merging**
