### PR TITLE
feat(compression): allow zstd-fast algorithm

### PR DESCRIPTION
**Pull request by Abhinandan-Purkait**
### Changes in the PR

- Adds the API changes to allow zstd-fast on regex.
- Simpify the regex to allow stems to have selective matching.
- Update manifests
- Adds a new test variant for zstd-fast

### Linked Issues
Fixes --> https://github.com/openebs/zfs-localpv/issues/501

### CODE REVIEW

**Review by niladrih — APPROVED** [review]
LGTM

**Comment by Abhinandan-Purkait** [comment]
Update on testing:-

1. Have tested upgrade from 2.6.1 to this and it works fine, without issues, though we would need a run from e2e as well. cc @w3aman 
2. The CI BDD test has passed with the change.

**Review by tiagolobocastro — APPROVED** [review]
tested regex and seems to work as expected, lgtm

**Comment by Abhinandan-Purkait** [comment]
Thanks folks, merging now.

**Pull request merged**
